#!/bin/sh

if [ $# -ne 3 ]; then
  printf 'usage: %s <device> <label> <fstype>\n' >&2
  exit 1
fi

DEV="$1"
LABEL="$2"
FSTYPE="$3"
BASEDIR='/d'
i=0
dir="${BASEDIR}/${LABEL}"
while [ -d "${dir}${i}" ] && /bin/mountpoint -q "${dir}${i}" && [ "$i" -lt 10 ]; do
  i=$((i+1))
done
if [ "$i" -eq 10 ]; then
  printf 'Max mount count reached\n' >&2
  exit 1
fi

mkdir -p "${dir}${i}"
mount -t "${FSTYPE}" "${DEV}" "${dir}${i}"
